document.write("<aside id = \"post_nav\">")
document.write("  <ul id=\"post_nav_0\" class=\"text-margin-tl\"><a href=\"#\", style=\"margin-right:4rem\" >git操作</a></ul>");
document.write("  <ul id=\"post_nav_1\" class=\"text-margin-l\"><a href=\"#\" , style=\"margin-right:4rem\" >前端html</a></ul>");
document.write("  <ul id=\"post_nav_2\" class=\"text-margin-l\"><a href=\"#\" , style=\"margin-right:4rem\" >js相关记录</a></ul>");
document.write("  <ul id=\"post_nav_3\" class=\"text-margin-l\"><a href=\"#\" , style=\"margin-right:4rem\" >python正则表达式</a></ul>");
document.write("  <ul id=\"post_nav_4\" class=\"text-margin-bl\"><a href=\"#\" , style=\"margin-right:4rem\">光流</a></ul>");
document.write("</aside>")
document.write("<article class=\"blog-post\" id=\"post_0\">");
document.write("    <h2>git操作</h2>");
document.write("    <p class=\"post-date\">2025年02月06日</p>");
document.write("<div id=\"post_content_0\" style=\"display:none\" >");
document.write('<p><strong>github与本地git管理</strong></p>\n<p>github在2021.08.13之后不再支持密码方式认证，可以通过SSH认证完成本地git仓库的上传</p>\n<p>1、需要修改本地仓库中的.git/config 中的URL路径，不再使用https而是使用git@github.com:xxxx/xxxxx.git的SSH地址（注意不加ssh://，直接从github网页copy）</p>\n<p>2、在本地的terminal下 ssh-keygen -t ed25519 -C "your_email@example.com"，来生成对应的SSH公钥和私钥文件（注意密钥文件的权限，777将无法使用，chmod 到600）</p>\n<p>3、eval "$(ssh-agent -s)"启动ssh服务</p>\n<p>4、ssh-add ~/.ssh/私钥文件</p>\n<p>5、在git hub setting中的的SSH keys增加相应的公钥文件中的内容</p>\n<p>6、稍等后完成，可以通过 ssh -vT git@github.com 来测试当前的连通</p>\n<p><strong>git个人命令整理</strong><br />\ngit pull --rebase<br />\ngit push<br />\ngit tag<br />\ngit stash<br />\ngit stash pop<br />\ngit reset --hard origin/master 慎用<br />\ngit checkout . #本地所有修改的。没有的提交的，都返回到原来的状态<br />\ngit stash #把所有没有提交的修改暂存到stash里面。可用git stash pop回复。<br />\ngit reset --hard HASH #返回到某个节点，不保留修改，已有的改动会丢失。<br />\ngit reset --soft HASH #返回到某个节点, 保留修改，已有的改动会保留，在未提交中，<br />\ngit status或git diff可看。<br />\ngit clean -df #返回到某个节点，（未跟踪文件的删除）<br />\ngit clean 参数 -n 不实际删除，只是进行演练，展示将要进行的操作，有哪些文件将要被删除。（可先使用该命令参数，然后再决定是否执行） <br />\n               -f 删除文件 <br />\n               -i 显示将要删除的文件 <br />\n               -d 递归删除目录及文件（未跟踪的） <br />\n               -q 仅显示错误，成功删除的文件不显示 <br />\n               注： git reset 删除的是已跟踪的文件，将已commit的回退。 git clean 删除的是未跟踪的文件<br />\ngit rebase -i HEAD~3：合并3笔提交<br />\ngit diff --name-only<br />\ngit diff --stat 简略信息</p>');
document.write("</div>");
document.write("</article>");
document.write("<article class=\"blog-post\" id=\"post_1\">");
document.write("    <h2>前端html</h2>");
document.write("    <p class=\"post-date\">2025年02月17日</p>");
document.write("<div id=\"post_content_1\" style=\"display:none\" >");
document.write('<p><strong>html布局</strong></p>\n<p>html通常由3部分组成：</p>\n<p>1、css样式表，通常单独存储，也可以在html中通过style标签进行内联覆盖</p>\n<p>2、html网页布局，网页的主体部分，体现了网页上通常有哪些元素</p>\n<p>3、JavaScript脚本，用于执行网页的特定功能</p>\n<p><strong>css使用技巧</strong></p>\n<p>在html的左右布局中，可以使用display:flex属性来使对应的元素弹性布局，从而便于自适应</p>');
document.write("</div>");
document.write("</article>");
document.write("<article class=\"blog-post\" id=\"post_2\">");
document.write("    <h2>js相关记录</h2>");
document.write("    <p class=\"post-date\">2025年02月18日</p>");
document.write("<div id=\"post_content_2\" style=\"display:none\" >");
document.write('<p><strong>js脚本相关</strong><br />\n可使用如下代码为元素增加相应的事件例如click,resize,onload等<br />\n添加成功后在chorme的 f12调试工具中可以看到对应的事件监视器，若未成功添加，则有可能存在：<br />\n1、对应元素未找到<br />\n2、script代码本身存在问题<br />\n3、父元素屏蔽了event</p>\n<pre><code class="language-javascript">    post_nav_display();\n    window.addEventListener(&quot;resize&quot;,post_nav_display);\n    function post_nav_display()\n    {\n        var post_nav = document.getElementById(&quot;post_nav&quot;);\n        if(post_nav.clientWidth &lt; 150){\n            post_nav.style.visibility = &quot;hidden&quot;;\n        }\n        else {\n            post_nav.style.visibility = &quot;visible&quot;;\n        }\n    }\n</code></pre>');
document.write("</div>");
document.write("</article>");
document.write("<article class=\"blog-post\" id=\"post_3\">");
document.write("    <h2>python正则表达式</h2>");
document.write("    <p class=\"post-date\">2025年02月19日</p>");
document.write("<div id=\"post_content_3\" style=\"display:none\" >");
document.write('<p><strong>re.findall(pattern,text)</strong><br />\nmatches = re.findall(pattern, text)<br />\nmatches结果为列表<br />\n(-\\w+): 匹配键，形如 -key。<br />\n(.*?): 非贪婪地捕获内容，直到下一个键开始或字符串结束。<br />\n(?= -\\w+|$): 使用前瞻确保匹配内容直到下一个键 -key 或字符串结束。</p>');
document.write("</div>");
document.write("</article>");
document.write("<article class=\"blog-post\" id=\"post_4\">");
document.write("    <h2>光流</h2>");
document.write("    <p class=\"post-date\">2025年02月25日</p>");
document.write("<div id=\"post_content_4\" style=\"display:none\" >");
document.write('<p><strong>光流算法</strong></p>\n<p>光流的概念是指在连续的两帧图像中由于图像中的物体移动或者摄像头的移动导致的图像中<strong>目标像素</strong>的移动<br />\n由观察者和场景之间的相对运动引起的视觉场景中物体表面和边缘的明显运动模式<br />\n光流是二维矢量场，表示了一个点从第一帧到第二帧的位移</p>\n<p>光流与运动向量概念类似，但又不同<br />\n总结对比表</p>\n<table>\n<thead>\n<tr>\n<th></th>\n<th><strong>光流</strong></th>\n<th><strong>运动向量</strong></th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>密度</td>\n<td>稠密（每个像素）</td>\n<td>稀疏（每个块）</td>\n</tr>\n<tr>\n<td>目标</td>\n<td>物理运动分析</td>\n<td>视频压缩效率</td>\n</tr>\n<tr>\n<td>计算复杂度</td>\n<td>高</td>\n<td>低（优化为实时编码）</td>\n</tr>\n<tr>\n<td>精度</td>\n<td>高（理论）</td>\n<td>低（工程折衷）</td>\n</tr>\n<tr>\n<td>应用领域</td>\n<td>计算机视觉、自动驾驶</td>\n<td>视频编码、流媒体传输</td>\n</tr>\n</tbody>\n</table>\n<p>光流法的工作原理基于如下假设：<br />\n1.亮度恒定，场景的像素强度在相邻帧之间基本不变<br />\n2.时间持续性，短时间变化不会导致为剧烈的位置变化，</p>\n<p>第一帧中像素I(x,y,t)表示t时刻坐标为(x,y)的像素值经过dt时间后会变成如下表达式</p>\n<p>$$I(x,y,t)=I(x+dx,y+dy,t+dt)$$</p>\n<p>假设移动很小，既取微元,使用泰勒展开</p>\n<p>$$I(x+dx,y+dy,t+dt)=I(x,y,t)+\\frac{\\partial I}{\\partial x} \\Delta x + \\frac{\\partial I}{\\partial y} \\Delta y + \\frac{\\partial I}{\\partial t} \\Delta t + H.O.T$$</p>\n<p>其中$H.O.T$为高阶无穷小<br />\n根据假设1有</p>\n<p>$$\\frac{\\partial I}{\\partial x} \\Delta x + \\frac{\\partial I}{\\partial y} \\Delta y + \\frac{\\partial I}{\\partial t} \\Delta t = 0$$</p>\n<p>两边同时除$\\Delta t$有</p>\n<p>$$\\frac{\\partial I}{\\partial x} \\frac{\\Delta x}{\\Delta t} + \\frac{\\partial I}{\\partial y} \\frac{\\Delta y}{\\Delta t} + \\frac{\\partial I}{\\partial t} = 0$$<br />\n既：<br />\n$$\\nabla I (x,y) + \\nabla I (t) = 0$$<br />\n也为：<br />\n$$I_x\\prime u  + I_y\\prime v + I_t\\prime = 0   , (\\begin{bmatrix}I_x\\prime \\ I_y\\prime \\end{bmatrix} \\begin{bmatrix}u&amp;&amp;v \\end{bmatrix}) = -\\Delta I_t  $$<br />\n其中(u，v)既为待求的光流</p>\n<p>参考文章：<br />\nhttps://zhuanlan.zhihu.com/p/74460341</p>');
document.write("</div>");
document.write("</article>");
